services:
  - type: web
    name: rtdb
    runtime: docker
    plan: free
    envVars:
      - key: STORAGE_DIR
        value: /data
      - key: BUCKET_NAME
        value: plygram/backend
      - key: HF_TOKEN
        sync: false
      - key: TF_CPP_MIN_LOG_LEVEL
        value: 2
      - key: PORT
        value: 8000
